### ISSUE TITLE
Could not convert DuckDB type: UNKNOWN to Postgres type

### ISSUE THREAD

**Issue by Leo-XM-Zeng** [duckdb/pg_duckdb#503] opened 2024-12-19 11:39 UTC
### What happens?

```plpgsql
[postgres@halo-centos8 pg_duckdb]$ psql test
psql (16.6)
Type "help" for help.

test=# create table t1(a int);
CREATE TABLE
test=# create table t2(b int);
CREATE TABLE
test=# INSERT INTO t1 SELECT generate_series(1, 10000);
INSERT 0 10000
test=# INSERT INTO t2 SELECT generate_series(1, 10000);
INSERT 0 10000
test=# set duckdb.force_execution = on;
SET
test=# \timing
Timing is on.
test=# PREPARE q1(int) AS
test-# SELECT count(*) FROM t1, t2 WHERE t1.a = t2.b or t1.a = t2.b + $1;
PREPARE
Time: 0.504 ms
test=# execute q1(100);
WARNING:  (PGDuckDB/GetPostgresDuckDBType) Could not convert DuckDB type: UNKNOWN to Postgres type
WARNING:  (PGDuckDB/CreatePlan) Cache lookup failed for type 0
 count 
-------
 19900
(1 row)

Time: 8883.252 ms (00:08.883)
``` 

### To Reproduce

```plpgsql
create table t1(a int);
create table t2(b int);
INSERT INTO t1 SELECT generate_series(1, 10000);
INSERT INTO t2 SELECT generate_series(1, 10000);
set duckdb.force_execution = on;
\timing
PREPARE q1(int) AS
SELECT count(*) FROM t1, t2 WHERE t1.a = t2.b or t1.a = t2.b + $1;
execute q1(100);
``` 

### OS:

centos8

### pg_duckdb Version (if built from source use commit hash):

main

### Postgres Version (if built from source use commit hash):

16.6

### Full Name:

Man Zeng

### Affiliation:

Halo

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by JelteF** [comment] 2024-12-19 11:52
Closing this, since it's a duplicate of #480

**Closed by JelteF** 2024-12-19 11:52 UTC

**Comment by Leo-XM-Zeng** [comment] 2024-12-19 12:02
> Closing this, since it's a duplicate of #480

Okay, sorry, I didn't notice there was already a similar problem~

**Comment by JelteF** [comment] 2024-12-19 13:11
No worries, thanks for the report. Please keep them coming. I'm just trying to keep the issue list free of duplicates.
