### ISSUE TITLE
Query lead to crash

### ISSUE THREAD

**Issue by Y--** [duckdb/pg_duckdb#245] opened 2024-10-03 12:43 UTC
This query crashes PG:
```
CREATE TABLE foo AS SELECT 'bar' AS t;
BEGIN; SET duckdb.execution = true; SELECT t::integer AS t1 FROM foo; ROLLBACK;
SET duckdb.execution = true; 
SELECT 1 FROM foo;
```

**Comment by JelteF** [comment] 2024-10-03 12:49
This specific issue is fixed in #231, because that starts to disallow duckdb queries transaction blocks. I also think that the simplification of our connection management logic due to removal of index scan support might resolve this too. Whenever we have something merged that fixes this we should add this as a regression test.

**Closed** 2024-10-04 12:39 UTC
Labels: bug
