### ISSUE TITLE
 ERROR, "Expected single table to be created, but found %" PRIu64, static_cast<uint64_t>

### ISSUE THREAD

**Issue by Dsyong123** [duckdb/pg_duckdb#441] opened 2024-11-17 07:06 UTC
### What happens?

compile  pg_duckdb extend occur  ERROR, "Expected single table to be created, but found %" PRIu64, static_cast<uint64_t>
PostgreSQL 15.5
gcc version 9.3.0 (GCC)

### To Reproduce
```
/* if we selected a row it was a duckdb table */
	auto is_duckdb_table = SPI_processed > 0;
	if (!is_duckdb_table) {
		/* No DuckDB tables were created so we don't need to do anything */
		AtEOXact_GUC(false, save_nestlevel);
		SPI_finish();
		PG_RETURN_NULL();
	}

	if (SPI_processed != 1) {
		elog(ERROR, "Expected single table to be created, but found %" PRIu64, static_cast<uint64_t>(SPI_processed));
	}
```
### OS:

CentOS Linux release 7.3.1611 (Core)

### pg_duckdb Version (if built from source use commit hash):

0.1.0

### Postgres Version (if built from source use commit hash):

PostgreSQL 15.5

### Hardware:

x86

### Full Name:

dsyang

### Affiliation:

oss

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by JelteF** [comment] 2024-11-17 22:52
You didn't provide any SQL commands that trigger this error. Please share the full commands. If it's an error during compilation please share the full error from the compiler, not just the code that causes the error.

**Comment by Dsyong123** [comment] 2024-11-17 22:52
这是来自QQ邮箱的假期自动回复邮件。您好，同学你的邮件我已收到

**Comment by JelteF** [comment] 2024-11-19 10:03
> OS:
>
> CentOS Linux release 7.3.1611 (Core)

I'm pretty sure this compilation failure is related to your OS being ancient. CentOS 7 has been End-Of-Life since June 30th 2024. So closing this, similarly to: https://github.com/duckdb/pg_duckdb/issues/133

Please re-open this issue if you can reproduce this on a supported OS.

**Closed by JelteF** 2024-11-19 10:03 UTC
